[package]
name = "gql-dyn"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
futures = "0.3.31"
juniper = "0.16.1"
juniper_axum = "0.2.0"
tokio = { version = "1.43", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
